apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherservice
  template:
    metadata:
      labels:
        app: weatherservice
    spec:
      containers:
        - name: weatherservice
          image: potatozhb1980/weatherservice:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weather-clusterip-srv
spec:
  selector:
    app: weatherservice
  ports:
    - name: weatherservice
      protocol: TCP
      port: 80
      targetPort: 8080

