apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  type: NodePort
  selector:
    app: weatherservice
  ports:
    - name: weatherservice
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31333
